#include <conio.h>
#include <iostream.h>
 
void main() {
clrscr();



cout<<"AAAAAAAAA     GGGGGGGGGG       UU      UU"<<endl;
cout<<"AAAAAAAAA     GGGGGGGGGG       UU      UU"<<endl;
cout<<"AA     AA     GG               UU      UU"<<endl;
cout<<"AA     AA     GG  GGGGGG       UU      UU"<<endl;
cout<<"AAAAAAAAA     GG  GGGGGG       UU      UU"<<endl;
cout<<"AA     AA     GG      GG       UU      UU"<<endl;
cout<<"AA     AA     GGGGGGGGGG       UUUUUUUUUU"<<endl;
cout<<"AA     AA     GGGGGGGGGG       UUUUUUUUUU"<<endl;
getch();
}

